name: EU Stream Recording

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: echo "Hello World - EU Stream Recorder works!"
