name: EU Stream Recording

on:
  schedule:
    - cron: '30 8 * * 1-5'  # Kör vardagar kl 10:30 svensk tid
  workflow_dispatch:        # Tillåt manuell körning

jobs:
  record-audio:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Create recordings directory
      run: mkdir -p recordings
    
    - name: Record EU Stream
      env:
        STREAM_URL: https://audiovisual.ec.europa.eu/en/ebs/live/2
      run: |
        python recorder.py
    
    - name: Upload recording
      uses: actions/upload-artifact@v4
      with:
        name: eu-stream-recording-${{ github.run_number }}
        path: recordings/
        retention-days: 30
